ignore_merge_commits = true

[version]
file = "VERSION"

pre_bump_hooks = [
    "echo {{version}}",
]


post_bump_hooks = [
    "echo {{version}} > VERSION", # Update the VERSION file
    "git add VERSION",
    "git commit -m 'ci: update VERSION file to {{version}}'",
    "git push",
    "git push origin {{version}}",
]
